version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    volumes:
      - ./client:/app/client
    command: npm run start
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb+srv://antonyaneric:Erik$2008@cluster0.hfvu6sp.mongodb.net/music-app?retryWrites=true&w=majority&appName=Cluster0
    command: npm run start:dev
    
